---
sidebar: sidebar 
permalink: task_signing_up_free_sandbox.html 
keywords: netapp, saas backup, salesforce, getting started, signing up, sso, free, sandbox, account 
summary: SaaS Backup for Salesforce の使用を開始するには、無料のサンドボックスアカウントにサインアップする必要があります。 
---
= Salesforce の無料サンドボックスアカウントにサインアップします
:toc: macro
:hardbreaks:
:toclevels: 1
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Salesforce サンドボックスアカウントを使用すると、本番環境に導入する前に、テスト環境で SaaS Backup for Salesforce の機能をテストできます。

.手順
. をクリックします link:https://www.salesforce.com/form/signup/freetrial-platform/["こちらをご覧ください"] 無料の Salesforce サンドボックスアカウントを起動します。
. 必要な情報を入力し、利用規約に同意して、「 * サインアップ * 」をクリックしてサインアッププロセスを完了します。
. メールアカウントに移動して確認し、新しいサンドボックスアカウントを確認します。表示されるリンクから、アカウントのパスワードを作成するように求められます。
. 新しく作成した Salesforce サンドボックスアカウントでは、 Lightning の体験とクラシックな体験を切り替えることができます。クラシックな体験に切り替えるには、 [ プロファイルの表示 ] をクリックし、 [*] をクリックして [Salesforce クラシックに切り替える *] をクリックします。これはオプションです。
. [* Setup * （セットアップ * ） ] タブをクリックします。
. 検索バーで「 * Users * 」を検索し、「 * Users * 」を選択します。ユーザープロファイル * システム管理者 * の名前は、このアカウントの電子メールです。
. この電子メールを選択し、 * パスワードをリセット * します。これは、サインアップではログインするための電子メールとパスワードが提供されないため、必須の手順です。
. パスワードをリセットしたら、この電子メールとパスワードを使用してサンドボックスにログインできます。



NOTE: 新しいアカウントには、サンプルのオブジェクトとレコードがあらかじめ入力されています。
